### ISSUE TITLE
Support Windows and Linux

### ISSUE THREAD

**Issue by dnet890** [Kurozora/kurozora-app#27]
Hi
I know macOS is good. But, it will be perfect if you are willing to support Windows and Linux as well. What do you think?

**Comment by kiritokatklian** [comment]
I'm guessing you're the same person from the Reddit thread. I just replied there, but I'll reply here too to keep a record for future visitors.

I’ve considered building native applications for Windows, Linux and Nintendo Switch before, but I put it on hold, because I won’t have the time and resources to support those the same way as with the website and iOS app.

The Mac app came to existence, because Apple made it easier to port iOS apps over to the Mac. So the iOS, iPadOS and MacOS is a single app that shares the same codebase.

All of my free time is currently occupied with developing the iOS app, website, and API. Also keeping the database up-to-date, since I don’t rely on third parties that much. I'd like Kurozora to continue working even when third parties have outages or simply cease to exist.

I’ve also received a lot of requests for an [Android](https://github.com/kurozora/kurozora-android) version, so I’m working on this too.

I’d love to have Kurozora on every platform available, but that’s a difficult task to pull off alone. I can’t promise it for now, but I will do it if there’s enough interest and there are people willing to help with developing it.

**Comment by LynxesExe** [comment]
I actually recent started contributing to Kurozora making a GTK4 app that will serve as a Desktop client for both Linux and Windows.

It's in a very early stage, but you can find it here: https://github.com/Kurozora/kurozora-linux

I'm closing this issue, since technically unrelated to this repository (iOS/macOS app), follow the linked repository for further updates.
